### ISSUE TITLE
undocumented filename requirement

### ISSUE THREAD

**Issue by amirtal-cp** [aleksanderaleksic/tgmigrate#17]
from readme:

> create a new file and name it something that makes sense for you.

but this will only work if the filename starts with a capital V, then some numbers, followed by '__', all without spaces.

**Comment by amirtal-cp** [comment]
also: thanks for this project! +1
initially found tfmigrate and then found this.

**Comment by aleksanderaleksic** [comment]
Thanks for the feedback @amirtal-cp , I will update the documentation ASAP
